apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            proxy_pass http://provisioner-auth:80/auth/login;
        }
        
        location /auth/login {
            proxy_pass http://provisioner-auth:80/auth/login;
        }
        
        location /dashboard {
            proxy_pass http://provisioner:80/provision/dashboard/;
        }
        
        location /static {
            proxy_pass http://provisioner:80/static;
        }
        
        location /provision/api {
            proxy_pass http://provisioner:80/provision/api;
        }
        
        location /api/get-redirect {
            proxy_pass http://provisioner:80/provision/api/get-redirect;
        }
        
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }

